triggers:
  - catchall

steps:
  - flow_set:
      question_entry_id: (@ flow.event.id )
      question: (@ flow.event.data.text )
  - typing: on

  - question: (@ flow.question )
    integration: integration.openai
    max_tokens: 300
    max_content_chunks: 8

  - value: (@ flow.error )
    case:
      no_content:
        jump: no_content
      timeout:
        jump: timeout
      internal:
        jump: error
    default: next

  - (answer)
  - say: (@ flow.answer )
    markdown: true
  - say: |
      (% for source in flow.sources %)
      * ##### (@ source )
      (% endfor %)
      ###### Powered by [GPT](https://docs.meya.ai/gpt). Was this response accurate or not?
    markdown: true
    quick_replies:
      - icon: streamline-light/22-social-medias-rewards-rating/04-likes/like.svg
        action:
          flow_set:
            rating: 1
      - icon: streamline-light/22-social-medias-rewards-rating/04-likes/dislike.svg
        action:
          flow_set:
            rating: -1

  - track: answer.rating
    data:
      answer_rating: (@ flow.rating )
      question_entry_id: (@ flow.question_entry_id )
      question: (@ flow.question )
      answer: (@ flow.answer )
      sources: (@ flow.sources )
  - end

  - (no_content)
  - say: Sorry, I don't know how to answer that. Can you rephrase it?
  - end

  - (timeout)
  - say: Sorry, I'm currently under heavy load, could you please try again later?
  - end

  - (error)
  - say: There was an error, our engineers are looking into it. Please try again later.
  - end
