triggers:
  - catchall

steps:
  - flow_set:
      question_entry_id: (@ flow.event.id )
      question: (@ flow.event.data.text )

  - thread_set:
      loading: true

  - typing: on
  - flow: flow.loading
    async: true

  - question: (@ flow.question )
    integration: integration.openai
    max_tokens: 300
    max_content_chunks: 8

  - thread_set:
      loading: false

  - value: (@ flow.error )
    case:
      no_content:
        jump: no_content
      timeout:
        jump: timeout
      internal:
        jump: error
    default: next

  - (answer)
  - say: |
      (@ flow.answer )
      ###### Powered by [MeyaGPT](https://www.meya.ai/product/meyagpt). Was this response accurate or not?
    markdown: true
    quick_replies:
      - text: Sources
        action:
          jump: sources
      - icon: streamline-light/22-social-medias-rewards-rating/04-likes/like.svg
        action:
          jump: rating
          data:
            rating: 1
      - icon: streamline-light/22-social-medias-rewards-rating/04-likes/dislike.svg
        action:
          jump: rating
          data:
            rating: -1

  - (sources)
  - say: |
      (% if flow.sources %)
      (% for source in flow.sources %)
      * ##### (@ source )
      (% endfor %)
      (% else %)
      No public links are available for this answer, as it was sourced internally.
      (% endif %)
    markdown: true
  - end

  - (rating)
  - track: answer.rating
    data:
      answer_rating: (@ flow.rating )
      question_entry_id: (@ flow.question_entry_id )
      question: (@ flow.question )
      answer: (@ flow.answer )
      sources: (@ flow.sources )
  - say: Thanks for your feedback!
    quick_replies:
      - text: Sources
        action:
          jump: sources
  - end

  - (no_content)
  - say: Sorry, I don't know how to answer that. Can you rephrase it?
  - end

  - (timeout)
  - say: Sorry, I'm currently under heavy load, could you please try again later?
  - end

  - (error)
  - say: There was an error, our engineers are looking into it. Please try again later.
  - end
